# Tutorial 3 - Data Importing and Cleaning

Packages to install:  
* `pandas`
* `matplotlib`

How to install:  
Running `!pip install pandas` and  `!pip install matplotlib` in one of the cell, and wait for the installation.

### Question 1

Based on the data below, do the following:  
    
1. Import necessary libraries
2. Load the data into a dataframe
3. Convert 'Date' column to datetime format
4. Check for missing values (use `isna`/`isnull` function)
5. Check for duplicates (use `duplicated` function)
6. Remove duplicates if any
7. Summary statistics (use the pandas `describe` function)
8. Calculate total sales amount
9. Save Cleaned Data

Data is below:

```
data = {
    'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05'],
    'Product': ['A', 'B', 'A', 'C', 'B'],
    'Price': [10, 20, 15, 25, 30],
    'Quantity': [100, 150, 200, 120, 180]
}
```

In [ ]:
!pip install pandas
!pip install matplotlib

In [ ]:
data = {
    'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05'],
    'Product': ['A', 'B', 'A', 'C', 'B'],
    'Price': [10, 20, 15, 25, 30],
    'Quantity': [100, 150, 200, 120, 180]
}
import pandas as pd
df = pd.DataFrame(data)
print(df)
df.Date = pd.to_datetime(df.Date)

is_duplicated = df.duplicated()
print(is_duplicated)

In [ ]:
stats = df.describe()
print(stats)

In [ ]:
total_sales = df['Price'] * df['Quantity']
print(total_sales)

### Question 2

Data cleaning using a CSV file containing information about online retail transactions.  
Based on the data, do the following:  

1. Save the provided data as `online_retail.csv` in the same directory as your Python script.
2. Import necessary libraries
3. Load the data from CSV
4. Check for missing values
5. Remove rows with missing values
6. Convert 'InvoiceDate' column to datetime format
7. Calculate the total transactions per country (using `groupby` function)
8. Plot a horizontal bar using `plot.barh` function 
9. Save the new data

In [ ]:
import matplotlib as plt
data = pd.read_csv('online_retail.csv')
data

In [ ]:
data = data.dropna()
data

In [ ]:
data.info()

In [ ]:
data.InvoiceDate = pd.to_datetime(data.InvoiceDate)
data.info()

In [ ]:
# Count transaction rows per country (each line item is a transaction record)
transactions_per_country = (
    data.groupby('Country')
    .size()
    .sort_values(ascending=False)
    .reset_index(name='TotalTransactions')
)

print(transactions_per_country.head(10))

In [ ]:
data.plot.barh()

### Question 3

The exercise will involve data cleaning, manipulation, and analysis tasks, including the use of the pivot() and melt() functions in Pandas:  

1. Load the data from the CSV file.
2. Perform data cleaning tasks such as handling missing values and data types.
3. Create additional columns for TotalPrice and YearMonth from the Timestamp column.
4. Aggregate the data to calculate total sales for each store and region.
5. Use the pivot() function to create a summary table showing total sales for each ProductName across different regions.
6. Use the melt() function to reshape the original data into a long format. The id columns are 'StoreID', 'Region', 'ProductID'
7. Save the manipulated data to new CSV files.

In [ ]:
data = pd.read_csv('sales_transactions.csv')
data.info()
data['Timestamp'] = pd.to_datetime(data['Timestamp'])
data.info()

In [ ]:
#Create additional columns for TotalPrice and YearMonth from the Timestamp column.
data['TotalPrice'] = data['Quantity'] * data['Price']
data['YearMonth'] = data['Timestamp'].dt.to_period('M')
data

In [ ]:
#Aggregate the data to calculate total sales for each store and region.

total_sales = data.groupby(['StoreID', 'Region'])['TotalPrice'].sum()
total_sales

In [ ]:
#Use the pivot() function to create a summary table showing total sales for each ProductName across different regions.
pivot_table = data.pivot(index='ProductName', columns='Region', values='TotalPrice').fillna(0)
pivot_table

In [ ]:
#Use the melt() function to reshape the original data into a long format. The id columns are 'StoreID', 'Region', 'ProductID'

melted_data = data.melt(id_vars=['StoreID', 'Region', 'ProductID'], var_name='Variable', value_name='Value')
melted_data
# Save the manipulated data to new CSV files
total_sales.to_csv('total_sales.csv')
pivot_table.to_csv('pivot_table.csv')
melted_data.to_csv('melted_data.csv', index=False)

### Question 4

The Excel file contains two sheets:

Student Scores: Contains columns for StudentID, Name, MathScore, PhysicsScore, ChemistryScore, and BiologyScore. Each row represents a student's scores in different subjects.  
Student Details: Contains additional details about each student, including StudentID, Name, Gender, Age, and Grade.

Task Description:

1. Load the data from the Student Scores and Student Details sheets in the Excel file.
2. Perform data cleaning tasks such as handling missing values and data types.
3. Merge the scores data with student details using StudentID as the key.
4. Calculate the average score for each student and add it as a new column.
5. Use the groupby() function to calculate average scores for each subject.
6. Use the pivot_table() function to create a summary table showing average scores for each subject by gender.
7. Use the melt() function to reshape the merged data into a long format.
    * ID columns are = 'StudentID', 'Name', 'Gender', 'Age', 'Grade'.
    * Melted columns are = 'MathScore', 'PhysicsScore', 'ChemistryScore', 'BiologyScore'
9. Save the manipulated data to a new Excel file.

In [56]:
!pip install openpyxl

scores_df = pd.read_excel('student_performance.xlsx', sheet_name='Student Scores')
details_df = pd.read_excel('student_performance.xlsx', sheet_name='Student Details')

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [57]:
print("Student Scores:")
print(scores_df.head())

print("\nStudent Details:")
print(details_df.head())

Student Scores:
   StudentID  MathScore  PhysicsScore  ChemistryScore  BiologyScore
0          1         66            77              82            81
1          2         66            79              71            71
2          3         68            90              71            70
3          4         89            63              92            62
4          5         95            82              91            91

Student Details:
   StudentID              Name  Gender  Age Grade
0          1      Casey Morris  Female   23     B
1          2      Jessica Hall  Female   23     B
2          3   Jerry Fernandez    Male   23     B
3          4  Kathryn Robinson  Female   18     B
4          5     Brett Delgado  Female   22     A

In [ ]:
# Check missing values
print("\nMissing values in Student Scores:")
print(scores_df.isnull().sum())

print("\nMissing values in Student Details:")
print(details_df.isnull().sum())

Missing values in Student Scores:
StudentID         0
MathScore         0
PhysicsScore      0
ChemistryScore    0
BiologyScore      0
dtype: int64

Missing values in Student Details:
StudentID    0
Name         0
Gender       0
Age          0
Grade        0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   StudentID       100 non-null    int64
 1   MathScore       100 non-null    int64
 2   PhysicsScore    100 non-null    int64
 3   ChemistryScore  100 non-null    int64
 4   BiologyScore    100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  100 non-null    int64
 1   Name       100 non-null    str
 2   Gender     100 non-null    str
 3   Age        100 non-null    int64
 4   Grade      100 non-null    str
dtypes: int64(2), str(3)
memory usage: 4.0 KB
None

In [ ]:
print(scores_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   StudentID       100 non-null    int64
 1   MathScore       100 non-null    int64
 2   PhysicsScore    100 non-null    int64
 3   ChemistryScore  100 non-null    int64
 4   BiologyScore    100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB
None

In [62]:
print(details_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  100 non-null    int64
 1   Name       100 non-null    str
 2   Gender     100 non-null    str
 3   Age        100 non-null    int64
 4   Grade      100 non-null    str
dtypes: int64(2), str(3)
memory usage: 4.0 KB
None

In [63]:
#Merge the scores data with student details using StudentID as the key.
merged_df = pd.merge(scores_df, details_df, on='StudentID', how='inner')
print(merged_df.head())

   StudentID  MathScore  PhysicsScore  ChemistryScore  BiologyScore  \
0          1         66            77              82            81
1          2         66            79              71            71
2          3         68            90              71            70
3          4         89            63              92            62
4          5         95            82              91            91

               Name  Gender  Age Grade
0      Casey Morris  Female   23     B
1      Jessica Hall  Female   23     B
2   Jerry Fernandez    Male   23     B
3  Kathryn Robinson  Female   18     B
4     Brett Delgado  Female   22     A

In [65]:
#Calculate the average score for each student and add it as a new column
merged_df['AvgScore'] = merged_df[['MathScore', 'PhysicsScore', 'ChemistryScore','BiologyScore']].mean(axis=1)
merged_df

,StudentID,MathScore,PhysicsScore,ChemistryScore,BiologyScore,Name,Gender,Age,Grade,AvgScore
0,1,66,77,82,81,Casey Morris,Female,23,B,76.50
1,2,66,79,71,71,Jessica Hall,Female,23,B,71.75
2,3,68,90,71,70,Jerry Fernandez,Male,23,B,74.75
3,4,89,63,92,62,Kathryn Robinson,Female,18,B,76.50
4,5,95,82,91,91,Brett Delgado,Female,22,A,89.75
...,...,...,...,...,...,...,...,...,...,...
95,96,66,68,82,100,Douglas Gray,Male,19,A,79.00
96,97,96,96,65,67,Jonathan Oliver,Female,24,C,81.00
97,98,60,67,94,63,Kathryn Mccarthy,Female,21,B,71.00
98,99,63,86,97,95,Lisa Ward,Female,18,B,85.25
99,100,60,96,89,62,Tyler Hayes,Female,18,B,76.75

In [66]:
#Use the groupby() function to calculate average scores for each subject.
subject_avg = merged_df[['MathScore', 'PhysicsScore', 'ChemistryScore','BiologyScore']].mean()
subject_avg.columns = ['Subject', 'AverageScore']
subject_avg

MathScore         78.99
PhysicsScore      79.59
ChemistryScore    79.95
BiologyScore      81.04
dtype: float64

In [67]:
#Use the pivot_table() function to create a summary table showing average scores for each subject by gender.
pivot_summary = pd.pivot_table(
    merged_df,
    values=['MathScore', 'PhysicsScore', 'ChemistryScore','BiologyScore'],
    index='Gender',
    aggfunc='mean'
)

pivot_summary

        BiologyScore  ChemistryScore  MathScore  PhysicsScore
Gender
Female     79.407407       80.703704  79.407407     80.055556
Male       82.956522       79.065217  78.500000     79.043478

In [72]:
#Use melt() to reshape the merged data into long format, 
# * ID columns are = 'StudentID', 'Name', 'Gender', 'Age', 'Grade'. 
# Melted columns are = 'MathScore', 'PhysicsScore', 'ChemistryScore', 'BiologyScore'

melted_df = pd.melt(
    merged_df,
    id_vars=['StudentID', 'Name', 'Gender', 'Age', 'Grade'],
    value_vars=['MathScore', 'PhysicsScore', 'ChemistryScore', 'BiologyScore'],
    var_name='Subject',
    value_name='Score'
)

melted_df.head(101)

     StudentID              Name  Gender  Age Grade       Subject  Score
0            1      Casey Morris  Female   23     B     MathScore     66
1            2      Jessica Hall  Female   23     B     MathScore     66
2            3   Jerry Fernandez    Male   23     B     MathScore     68
3            4  Kathryn Robinson  Female   18     B     MathScore     89
4            5     Brett Delgado  Female   22     A     MathScore     95
..         ...               ...     ...  ...   ...           ...    ...
96          97   Jonathan Oliver  Female   24     C     MathScore     96
97          98  Kathryn Mccarthy  Female   21     B     MathScore     60
98          99         Lisa Ward  Female   18     B     MathScore     63
99         100       Tyler Hayes  Female   18     B     MathScore     60
100          1      Casey Morris  Female   23     B  PhysicsScore     77

[101 rows x 7 columns]

In [73]:
with pd.ExcelWriter('student_performance_analysis.xlsx') as writer:
    merged_df.to_excel(writer, sheet_name='MergedData', index=False)
    subject_avg.to_excel(writer, sheet_name='SubjectAverages')
    pivot_summary.to_excel(writer, sheet_name='PivotSummary')
    melted_df.to_excel(writer, sheet_name='MeltedData', index=False)